#!/bin/bash

service --status-all
read -p 'do you want to start or stop a service ?: ' var

if [ $var == "start" ]
then
	read -p 'what service to start ? ' ser
	service $ser start
elif [ $var == "stop" ]
then
	read -p 'what service to stop ? ' ser
	service $ser stop
else
	echo "wrong keyword"
fi
